# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: './src/minsk.sln'
  tests: './src/Minsk.Tests/Minsk.Tests.csproj'

steps:
- task: UseDotNet@2
  displayName: Use .NET 5.0 Preview
  inputs:
    version: 5.0.x
    packageType: sdk
    includePreviewVersions: true
# We now still need .NET Core 3.1 Runtime for CI tests
- task: UseDotNet@2
  displayName: Install .NET Core 3.1 Runtime
  inputs:
    version: 3.1.x
    packageType: runtime
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: build
    projects: $(sln)
    arguments: --configuration $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: $(tests)
    arguments: --configuration $(buildConfiguration)
    publishTestResults: true
